app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::auth();

Route::get('/', 'HomeController@index');
//pusher
Route::get('users/event-user', 'UserController@user');

//Autocomplete
Route::get('autocomplete/users', 'AutoCompleteController@users');
Route::get('autocomplete/leave_types', 'AutoCompleteController@leave_types');
Route::get('autocomplete/departments', 'AutoCompleteController@departments');
Route::get('autocomplete/designation_items', 'AutoCompleteController@designation_items');
Route::get('autocomplete/document_types', 'AutoCompleteController@document_types');
Route::get('autocomplete/roles', 'AutoCompleteController@roles');

//Route::resource('absences', 'AbsenceController');
Route::get('absences', 'AbsenceController@index');
Route::get('absences/search', 'AbsenceController@search');
Route::get('absences/create', 'AbsenceController@create');
Route::post('absences', 'AbsenceController@store');
Route::get('absences/{absence}', 'AbsenceController@show');
Route::get('absences/{absence}/edit', 'AbsenceController@edit');
Route::patch('absences/{absence}', 'AbsenceController@update');
Route::delete('absences/{absence}', 'AbsenceController@destroy');

//Route::resource('attendances', 'AttendanceController');
Route::get('attendances', 'AttendanceController@index');
Route::get('attendances/search', 'AttendanceController@search');
Route::get('attendances/create', 'AttendanceController@create');
Route::post('attendances', 'AttendanceController@store');
Route::get('attendances/{attendance}', 'AttendanceController@show');
Route::get('attendances/{attendance}/edit', 'AttendanceController@edit');
Route::patch('attendances/{attendance}', 'AttendanceController@update');
Route::delete('attendances/{attendance}', 'AttendanceController@destroy');

//Route::resource('awards', 'AwardController');
Route::get('awards', 'AwardController@index');
Route::get('awards/search', 'AwardController@search');
Route::get('awards/create', 'AwardController@create');
Route::post('awards', 'AwardController@store');
Route::get('awards/{award}', 'AwardController@show');
Route::get('awards/{award}/edit', 'AwardController@edit');
Route::patch('awards/{award}', 'AwardController@update');
Route::delete('awards/{award}', 'AwardController@destroy');

//Route::resource('bank-accounts', 'BankAccountController');
Route::get('bank-accounts', 'BankAccountController@index');
Route::get('bank-accounts/search', 'BankAccountController@search');
Route::get('bank-accounts/create', 'BankAccountController@create');
Route::post('bank-accounts', 'BankAccountController@store');
Route::get('bank-accounts/{bank_account}', 'BankAccountController@show');
Route::get('bank-accounts/{bank_account}/edit', 'BankAccountController@edit');
Route::patch('bank-accounts/{bank_account}', 'BankAccountController@update');
Route::delete('bank-accounts/{bank_account}', 'BankAccountController@destroy');

//Route::resource('cut-offs', 'CutOffController');
Route::get('cut-offs', 'CutOffController@index');
Route::get('cut-offs/search', 'CutOffController@search');
Route::get('cut-offs/create', 'CutOffController@create');
Route::post('cut-offs', 'CutOffController@store');
Route::get('cut-offs/{cut_off}', 'CutOffController@show');
Route::get('cut-offs/{cut_off}/edit', 'CutOffController@edit');
Route::patch('cut-offs/{cut_off}', 'CutOffController@update');
Route::delete('cut-offs/{cut_off}', 'CutOffController@destroy');

//Route::resource('departments', 'DepartmentController');
Route::get('departments', 'DepartmentController@index');
Route::get('departments/search', 'DepartmentController@search');
Route::get('departments/create', 'DepartmentController@create');
Route::post('departments', 'DepartmentController@store');
Route::get('departments/{department}', 'DepartmentController@show');
Route::get('departments/{department}/edit', 'DepartmentController@edit');
Route::patch('departments/{department}', 'DepartmentController@update');
Route::delete('departments/{department}', 'DepartmentController@destroy');

Route::get('departments/{department}/designation-items/create', 'DesignationItemController@create');
Route::post('departments/{department}/designation-items', 'DesignationItemController@store');
Route::get('departments/{department}/designation-items/{designation_item}/edit', 'DesignationItemController@edit');
Route::patch('departments/{department}/designation-items/{designation_item}', 'DesignationItemController@update');
Route::delete('departments/{department}/designation-items/{designation_item}', 'DesignationItemController@destroy');

//Route::resource('designations', 'DesignationController');
Route::get('designations', 'DesignationController@index');
Route::get('designations/search', 'DesignationController@search');
Route::get('designations/create', 'DesignationController@create');
Route::post('designations', 'DesignationController@store');
Route::get('designations/{designation}', 'DesignationController@show');
Route::get('designations/{designation}/edit', 'DesignationController@edit');
Route::patch('designations/{designation}', 'DesignationController@update');
Route::delete('designations/{designation}', 'DesignationController@destroy');

//Route::resource('designation-items', 'DesignationItemController');
Route::get('designation-items', 'DesignationItemController@index');
Route::get('designation-items/search', 'DesignationItemController@search');
Route::get('designation-items/create', 'DesignationItemController@create');
Route::post('designation-items', 'DesignationItemController@store');
Route::get('designation-items/{designation_item}', 'DesignationItemController@show');
Route::get('designation-items/{designation_item}/edit', 'DesignationItemController@edit');
Route::patch('designation-items/{designation_item}', 'DesignationItemController@update');
Route::delete('designation-items/{designation_item}', 'DesignationItemController@destroy');

//Route::resource('documents', 'DocumentController');
Route::get('documents', 'DocumentController@index');
Route::get('documents/search', 'DocumentController@search');
Route::get('documents/create', 'DocumentController@create');
Route::post('documents', 'DocumentController@store');
Route::get('documents/{document}', 'DocumentController@show');
Route::get('documents/{document}/edit', 'DocumentController@edit');
Route::patch('documents/{document}', 'DocumentController@update');
Route::delete('documents/{document}', 'DocumentController@destroy');

//Route::resource('payroll_templates', 'PayrollTemplateController');
Route::get('payroll-templates', 'PayrollTemplateController@index');
Route::get('payroll-templates/search', 'PayrollTemplateController@search');
Route::get('payroll-templates/create', 'PayrollTemplateController@create');
Route::post('payroll-templates', 'PayrollTemplateController@store');

Route::get('payroll-templates/{payroll_template}', 'PayrollTemplateController@show');
Route::get('payroll-templates/{payroll_template}/edit', 'PayrollTemplateController@edit');
Route::patch('payroll-templates/{payroll_template}', 'PayrollTemplateController@update');
Route::delete('payroll-templates/{payroll_template}', 'PayrollTemplateController@destroy');

Route::get('salary-details', 'SalaryDetailController@index');
Route::any('/salary-details/get_employees', [
    'as' => '/salary-details/get_employees', 
    'uses' => 'SalaryDetailController@get_employees'
    ]);
Route::any('/salary-details/save_salary_details', [
    'as' => '/salary-details/save_salary_details', 
    'uses' => 'SalaryDetailController@save_salary_details'
    ]);

Route::get('salary-list', 'SalaryListController@index');

//Route::resource('document-types', 'DocumentTypeController');
Route::get('document-types', 'DocumentTypeController@index');
Route::get('document-types/search', 'DocumentTypeController@search');
Route::get('document-types/create', 'DocumentTypeController@create');
Route::post('document-types', 'DocumentTypeController@store');
Route::get('document-types/{document_type}', 'DocumentTypeController@show');
Route::get('document-types/{document_type}/edit', 'DocumentTypeController@edit');
Route::patch('document-types/{document_type}', 'DocumentTypeController@update');
Route::delete('document-types/{document_type}', 'DocumentTypeController@destroy');

//Route::resource('events', 'EventController');
Route::get('events', 'EventController@index');
Route::get('events/search', 'EventController@search');
Route::get('events/create', 'EventController@create');
Route::post('events', 'EventController@store');
Route::get('events/{event}', 'EventController@show');
Route::get('events/{event}/edit', 'EventController@edit');
Route::patch('events/{event}', 'EventController@update');
Route::delete('events/{event}', 'EventController@destroy');

//Route::resource('expenses', 'ExpenseController');
Route::get('expenses', 'ExpenseController@index');
Route::get('expenses/search', 'ExpenseController@search');
Route::get('expenses/create', 'ExpenseController@create');
Route::post('expenses', 'ExpenseController@store');
Route::get('expenses/{expense}', 'ExpenseController@show');
Route::get('expenses/{expense}/edit', 'ExpenseController@edit');
Route::patch('expenses/{expense}', 'ExpenseController@update');
Route::delete('expenses/{expense}', 'ExpenseController@destroy');

//Route::resource('holidays', 'HolidayController');
Route::get('holidays', 'HolidayController@index');

app/Notice.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

use Carbon\Carbon;

class Notice extends Model
{
    use SoftDeletes;
	
	protected $dates = ['deleted_at'];
	
	protected $fillable = [
		'published',
		'title',
		'description',
		'image',
	];
	
	public function getCreatedAtAttribute($date){
		return Carbon::parse($date)->format('m/d/Y');
	}
	
	public function setImageAttribute($value)
	{
		if(empty($value)){
			$this->attributes['image'] = '';
		}else{
			$ext = $value->getClientOriginalExtension();
			$filename = str_random(12).'.'.$ext;
			\Image::make($value)->resize(50, null, function ($constraint) {
				$constraint->aspectRatio();
			})->crop(50, 50)->save(public_path('dist/img/notices/'.$filename));
			$this->attributes['image'] = 'dist/img/notices/'.$filename;
		}
	}
	
	public function getImageAttribute($value)
	{
		return $value != NULL ? $value : 'dist/img/default-50x50.gif';
	}
}

resources/views/home.blade.php
@extends(Auth::check() && Auth::user()->role->layout == 1 ? 'layouts.admin' : 'layouts.employee')

@section('content')
<div class="content-wrapper">

	<section class="content">
		<?php /* <a class="btn btn-app btn-flat bg-green" href="{{ asset('/users/'.$user->id.'/edit') }}"><i class="fa fa-edit"></i> Edit</a>
		<a class="btn btn-app btn-flat bg-green" href="{{ asset('/users/'.$user->id.'/absences/create') }}"><i class="fa fa-user-times"></i> Absence</a>
		<a class="btn btn-app btn-flat bg-green" href="{{ asset('/users/'.$user->id.'/awards/create') }}"><i class="fa fa-trophy"></i> Award</a>
		<a class="btn btn-app btn-flat bg-green" href="{{ asset('/users/'.$user->id.'/documents/create') }}"><i class="fa fa-file"></i> Document</a>
		<a class="btn btn-app btn-flat bg-green" href="{{ asset('/users/'.$user->id.'/expenses/create') }}"><i class="fa fa-money"></i> Expense</a>
		<a class="btn btn-app btn-flat bg-green" href="{{ asset('/users/'.$user->id.'/leaves/create') }}"><i class="fa fa-rocket"></i> Leave</a>
		<a class="btn btn-app btn-flat bg-green" href="{{ asset('/users/'.$user->id.'/bank-account/create') }}"><i class="fa fa-bank"></i> Bank Account</a> */ ?>
	<div class="row">
			<!--<div class="col-md-3">
				<div class="box box-success">
					<div class="box-body box-profile">
						<img class="profile-user-img img-responsive img-circle" src="{{ asset(Auth::user()->profile_picture) }}" alt="User profile picture">
						<h3 class="profile-username text-center">{{ Auth::user()->first_name.' '.Auth::user()->last_name }}</h3>
						<p class="text-center no-margin">{{ Auth::user()->designation_item ? Auth::user()->designation_item->designation_item : '' }}</p>
						<p class="small text-center no-margin"><span class="text-muted">Department:</span> {{ Auth::user()->department ? Auth::user()->department->department : '' }}</p>
						<p class="small text-center no-margin"><span class="text-muted">Employee ID:</span> {{ Auth::user()->employee_id }}</p>
					</div>
					<div class="box-footer">
						<div class="row">
							<div class="col-sm-4 border-right">
								<div class="description-block">
								<h5 class="description-header">8/11</h5>
								<span class="description-text small">Attendance</span>
								</div>
							</div>
							<div class="col-sm-6 border-right">
								<div class="description-block">
								<h5 class="description-header">{{ Auth::user()->leaves->count() }}</h5>
								<span class="description-text small">Leave</span>
								</div>
							</div>
							<div class="col-sm-6">
								<div class="description-block">
								<h5 class="description-header">{{ Auth::user()->awards->count() }}</h5>
								<span class="description-text small">Awards</span>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="small-box bg-black">
					<div class="inner datebar" align="center">
						<p><?php echo date('l'). ", " .date('jS \of F, Y'); ?></p>
						<h3 id="clock"></h3>
						<br />
					</div>
				</div>
			</div>-->
			<!--<div class="col-md-9">
				<div class="row">
					<div class="col-md-6">
						<div class="box box-success">
							<div class="box-header">
								<h3 class="box-title">Personal Details</h3>
							</div>
							<div class="box-body no-padding">
								<table class="table">
									<tbody>
									<tr>
										<td style="width: 10px" class="text-center"><i class="fa fa-birthday-cake"></i></td>
										<td><strong>Birthday</strong></td>
										<td>{{ Auth::user()->birthday }}</td>
									</tr>
									<tr>
										<td style="width: 10px" class="text-center"><i class="fa fa-genderless"></i></td>
										<td><strong>Gender</strong></td>
										<td>{{ Auth::user()->gender_text() }}</td>
									</tr>
									<tr>
										<td style="width: 10px" class="text-center"><i class="fa fa-envelope-o"></i></td>
										<td><strong>Email</strong></td>
										<td>{{ Auth::user()->email }}</td>
									</tr>
									<tr>
										<td style="width: 10px" class="text-center"><i class="fa fa-phone"></i></td>
										<td><strong>Telephone</strong></td>
										<td>{{ Auth::user()->telephone }}</td>
									</tr>
									<tr>
										<td style="width: 10px" class="text-center"><i class="fa fa-mobile-phone"></i></td>
										<td><strong>Cellphone</strong></td>
										<td>{{ Auth::user()->cellphone }}</td>
									</tr>
									<tr>
										<td style="width: 10px" class="text-center"><i class="fa fa-map-marker"></i></td>
										<td><strong>Local Address</strong></td>
										<td>{{ Auth::user()->local_address }}</td>
									</tr>
									<tr>
										<td style="width: 10px" class="text-center"><i class="fa fa-map-marker"></i></td>
										<td><strong>Permanent Address</strong></td>
										<td>{{ Auth::user()->permanent_address }}</td>
									</tr>
									</tbody>
								</table>
							</div>
						</div>
						<div class="box box-success">
							<div class="box-header">
								<h3 class="box-title">Company Details</h3>
							</div>
							<div class="box-body no-padding">
								<table class="table">
									<tbody>
									<tr>
										<td style="width: 10px" class="text-center"><i class="fa fa-key"></i></td>
										<td><strong>Employee ID</strong></td>
										<td>{{ Auth::user()->employee_id }}</td>
									</tr>
									<tr>
										<td class="text-center"><i class="fa fa-briefcase"></i></td>
										<td><strong>Department</strong></td>
										<td>{{ Auth::user()->department ? Auth::user()->department->department : '' }}</td>
									</tr>
									<tr>
										<td class="text-center"><i class="fa fa-cubes"></i></td>
										<td><strong>Designation</strong></td>
										<td>{{ Auth::user()->designation_item ? Auth::user()->designation_item->designation_item : '' }}</td>
									</tr>
									<tr>
										<td class="text-center"><i class="fa fa-calendar-check-o"></i></td>
										<td><strong>Date Hired</strong></td>
										<td>{{ Auth::user()->date_hired }}</td>
									</tr>
									<tr>
										<td class="text-center"><i class="fa fa-credit-card"></i></td>
										<td><strong>Salary</strong></td>
										<td>{{ Auth::user()->salary }}</td>
									</tr>
									</tbody>
								</table>
							</div>
						</div>
						<div class="box box-success">
							<div class="box-header">
								<h3 class="box-title">Bank Details</h3>
							</div>
							<div class="box-body no-padding">
								<table class="table">
									<tbody>
									<tr>
										<td style="width: 10px" class="text-center"><i class="fa fa-credit-card-alt"></i></td>
										<td><strong>Account Name</strong></td>
										<td>{{ Auth::user()->bank_account ? Auth::user()->bank_account->account_name : '' }}</td>
									</tr>
									<tr>
										<td style="width: 10px" class="text-center"><i class="fa fa-hashtag"></i></td>
										<td><strong>Account Number</strong></td>
										<td>{{ Auth::user()->bank_account ? Auth::user()->bank_account->account_number : '' }}</td>
									</tr>
									<tr>
										<td style="width: 10px" class="text-center"><i class="fa fa-bank"></i></td>
										<td><strong>Bank Name</strong></td>
										<td>{{ Auth::user()->bank_account ? Auth::user()->bank_account->bank_name : '' }}</td>
									</tr>
									</tbody>
								</table>
							</div>
						</div>
					</div>-->
					<!--<div class="col-md-6">
						<div class="box box-success">
							<div class="box-header with-border">
								<h3 class="box-title"><i class="fa fa-bell-o"></i> Notice Board</h3>
							</div>
							<div class="box-body">
								<ul class="products-list product-list-in-box">
									@foreach($notices as $notice)
									<li class="item">
										<div class="product-img">
											<img src="{{ asset($notice->image) }}" alt="Product Image">
										</div>
										<div class="product-info">
											<a href="{{ asset('notices/'.$notice->id) }}" class="product-title">{{ $notice->title }}
											<span class="label label-success pull-right">{{ $notice->created_at }}</span></a>
											<span class="product-description">
											{{ $notice->description }}
											</span>
										</div>
									</li>
									@endforeach
								</ul>
							</div>
							<div class="box-footer text-center">
								<a href="{{ asset('notices') }}" class="uppercase">View All</a>
							</div>
						</div>-->
						<!--<div class="box box-success">
							<div class="box-header with-border">
								<h3 class="box-title"><i class="fa fa-calendar-o"></i> Upcoming Events</h3>
							</div>
							<div class="box-body">
								<ul class="products-list product-list-in-box">
									@foreach($events as $event)
									<li class="item">
										<div class="product-img">
											<img src="{{ asset($event->image) }}" alt="Product Image">
										</div>
										<div class="product-info">
											<a href="{{ asset('events/'.$event->id) }}" class="product-title">{{ $event->event_name }}
											<span class="label label-success pull-right">{{ $event->date_start }}</span></a>
											<span class="product-description">
											{{ $event->description }}
											</span>
										</div>
									</li>
									@endforeach
								</ul>
							</div>
							<div class="box-footer text-center">
								<a href="{{ asset('events') }}" class="uppercase">View All</a>
							</div>
						</div>
					</div>-->
				</div>
			</div>
		</div>
	</section>
</div>
@endsection

@section('foot')
	<script type="text/javascript">
		function startTime() {
			var today=new Date(),
			curr_hour=today.getHours(),
			curr_min=today.getMinutes(),
			curr_sec=today.getSeconds();
			curr_hour=checkTime(curr_hour);
			curr_min=checkTime(curr_min);
			curr_sec=checkTime(curr_sec);
			document.getElementById('clock').innerHTML=curr_hour+":"+curr_min+":"+curr_sec;
		}
		function checkTime(i) {
			if (i<10) {
				i="0" + i;
			}
			return i;
		}
		setInterval(startTime, 500);
	</script>
@endsection